package global_configs

const HEADERlENGTH = 4

const UPLOADINITOPCODE = 0
const UPLOADCHUNKOPCODE = 1
const UPLOADFINISHOPCODE = 2
const UPLOADCANCELOPCODE = 3
const UPLOADRETRANSMISSIONOPCODE = 4

const CHUNKJOBWORKERPOOL = 4
const CHUNKJOBERRPOOL = CHUNKJOBWORKERPOOL * 2
const CHUNKJOBCONFIRMATIONPOOL = CHUNKJOBERRPOOL * 2

const CHUNKJOBCONFIRMATIONWORKERPOOL = 1
const CHUNKJOBERRWORKERPOOL = 1

const CHUNKJOBCHANNELBUFFERSIZE = 10

const CHUNKUPLOADROOTFOLDERPATH = "chunk_uploads"
