package global_configs

import "path/filepath"

const HEADERlENGTH = 4

const UPLOADINITOPCODE = 0
const UPLOADCHUNKOPCODE = 1
const UPLOADFINISHOPCODE = 2
const UPLOADCANCELOPCODE = 3
const UPLOADRETRANSMISSIONOPCODE = 4

const CHUNKJOBWORKERPOOL = 4
const CHUNKJOBERRPOOL = CHUNKJOBWORKERPOOL * 2
const CHUNKJOBCONFIRMATIONPOOL = CHUNKJOBERRPOOL * 2

const CHUNKJOBCONFIRMATIONWORKERPOOL = 1
const CHUNKJOBERRWORKERPOOL = 1

const CHUNKJOBCHANNELBUFFERSIZE = 10

const SERVICESTATUSNOTIFICATIONCHANNELBUFFER = 5

var cHUNKUPLOADROOTFOLDER string = "chunk_uploads"
var uPLOADROOT string = "upload_root"

//var CHUNKUPLOADROOTFOLDERPATH string = filepath.Join(uPLOADROOT, cHUNKUPLOADROOTFOLDER)
func CHUNKUPLOADROOTFOLDERPATH() string {
	return filepath.Join(uPLOADROOT, cHUNKUPLOADROOTFOLDER)
}
